# -*- coding: utf-8 -*-
"""halo_dunia.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lodPTZyogdxX_7SxxlE0pC2xjK30pwi7
"""

print('Halo Dunia !')